[tool.poetry]
name = "shamir-secret-sharing-example"
version = "0.1.0"
description = ""
authors = ["a <a>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sympy = "^1.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
